version: "3.8"

services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend

  backend:
    build:
      context: ./server
    ports:
      - "3000:3000"
      - "3001:3001"
    environment:
      - NODE_ENV=production
